// Plain names for 4-digit CIP codes. The official CIP titles are long ("Registered
// Nursing, Nursing Administration, Nursing Research and Clinical Nursing."), so
// pages use these short names in titles, headings, and sentences.
//
// `name` is used in titles and headings. Inside sentences the name is lowercased
// word by word, keeping words written in capitals (HVAC, IT). `sentenceName`
// overrides that when a word must stay capitalized (English, Bible).
//
// Every CIP code that gets a page, or that shows up in a school's table of
// programs, must be listed here. The data script stops if one is
// missing.

export type FieldName = {
  name: string
  sentenceName?: string
}

export const FIELD_NAMES: Record<string, FieldName> = {
  '0100': { name: 'Agriculture' },
  '0101': { name: 'Agricultural Business' },
  '0102': { name: 'Agricultural Mechanization' },
  '0103': { name: 'Agricultural Production' },
  '0104': { name: 'Food Processing' },
  '0105': { name: 'Animal Services' },
  '0106': { name: 'Applied Horticulture' },
  '0107': { name: 'International Agriculture' },
  '0108': { name: 'Agricultural Public Services' },
  '0109': { name: 'Animal Science' },
  '0110': { name: 'Food Science' },
  '0111': { name: 'Plant Science' },
  '0112': { name: 'Soil Science' },
  '0113': { name: 'Pre-Veterinary Studies' },
  '0181': { name: 'Veterinary Science' },
  '0183': { name: 'Veterinary Technology' },
  '0199': { name: 'Other Agriculture' },
  '0301': { name: 'Environmental Science and Conservation' },
  '0302': { name: 'Environmental Management and Policy' },
  '0303': { name: 'Fisheries Science' },
  '0305': { name: 'Forestry' },
  '0306': { name: 'Wildlife Science' },
  '0399': { name: 'Other Natural Resources' },
  '0402': { name: 'Architecture' },
  '0403': { name: 'Urban and Regional Planning' },
  '0404': { name: 'Environmental Design' },
  '0405': { name: 'Interior Architecture' },
  '0406': { name: 'Landscape Architecture' },
  '0408': { name: 'Architectural History' },
  '0409': { name: 'Architectural Technology' },
  '0410': { name: 'Real Estate Development' },
  '0499': { name: 'Other Architecture' },
  '0501': { name: 'Area Studies' },
  '0502': { name: 'Ethnic, Cultural, and Gender Studies' },
  '0901': { name: 'Communications' },
  '0904': { name: 'Journalism' },
  '0907': { name: 'Radio, TV, and Digital Media' },
  '0909': { name: 'Public Relations and Advertising' },
  '0910': { name: 'Publishing' },
  '0999': { name: 'Other Communication and Journalism' },
  '1001': { name: 'Communications Technology' },
  '1002': { name: 'Audiovisual Technology' },
  '1003': { name: 'Graphic Communications' },
  '1099': { name: 'Other Communications Technology' },
  '1101': { name: 'Computer and Information Science' },
  '1102': { name: 'Computer Programming' },
  '1103': { name: 'Data Processing' },
  '1104': { name: 'Information Science' },
  '1105': { name: 'Computer Systems Analysis' },
  '1106': { name: 'Data Entry and Computer Applications' },
  '1107': { name: 'Computer Science' },
  '1108': { name: 'Software and Media Applications' },
  '1109': { name: 'Computer Networking' },
  '1110': { name: 'Information Technology' },
  '1199': { name: 'Other Computer Sciences' },
  '1203': { name: 'Funeral Service and Mortuary Science' },
  '1204': { name: 'Cosmetology' },
  '1205': { name: 'Culinary Arts' },
  '1299': { name: 'Other Personal Services' },
  '1301': { name: 'Education' },
  '1302': { name: 'Bilingual Education' },
  '1303': { name: 'Curriculum and Instruction' },
  '1304': { name: 'Educational Administration' },
  '1305': { name: 'Instructional Design' },
  '1306': { name: 'Educational Assessment and Research' },
  '1307': { name: 'International Education' },
  '1309': { name: 'Foundations of Education' },
  '1310': { name: 'Special Education' },
  '1312': { name: 'Teacher Education' },
  '1313': { name: 'Subject-Area Teacher Education' },
  '1314': { name: 'ESL Teaching', sentenceName: 'ESL teaching' },
  '1315': { name: 'Teaching Assistant Training' },
  '1399': { name: 'Other Education' },
  '1401': { name: 'Engineering' },
  '1402': { name: 'Aerospace Engineering' },
  '1403': { name: 'Agricultural Engineering' },
  '1404': { name: 'Architectural Engineering' },
  '1405': { name: 'Biomedical Engineering' },
  '1406': { name: 'Ceramic Engineering' },
  '1407': { name: 'Chemical Engineering' },
  '1408': { name: 'Civil Engineering' },
  '1409': { name: 'Computer Engineering' },
  '1410': { name: 'Electrical Engineering' },
  '1411': { name: 'Engineering Mechanics' },
  '1412': { name: 'Engineering Physics' },
  '1413': { name: 'Engineering Science' },
  '1414': { name: 'Environmental Engineering' },
  '1418': { name: 'Materials Engineering' },
  '1419': { name: 'Mechanical Engineering' },
  '1420': { name: 'Metallurgical Engineering' },
  '1421': { name: 'Mining Engineering' },
  '1422': { name: 'Naval Architecture and Marine Engineering' },
  '1423': { name: 'Nuclear Engineering' },
  '1424': { name: 'Ocean Engineering' },
  '1425': { name: 'Petroleum Engineering' },
  '1427': { name: 'Systems Engineering' },
  '1428': { name: 'Textile Engineering' },
  '1432': { name: 'Polymer and Plastics Engineering' },
  '1433': { name: 'Construction Engineering' },
  '1434': { name: 'Forest Engineering' },
  '1435': { name: 'Industrial Engineering' },
  '1436': { name: 'Manufacturing Engineering' },
  '1437': { name: 'Operations Research' },
  '1438': { name: 'Surveying Engineering' },
  '1439': { name: 'Geological Engineering' },
  '1440': { name: 'Paper Science and Engineering' },
  '1441': { name: 'Electromechanical Engineering' },
  '1442': { name: 'Mechatronics and Robotics Engineering' },
  '1443': { name: 'Biochemical Engineering' },
  '1445': { name: 'Biological Engineering' },
  '1499': { name: 'Other Engineering' },
  '1500': { name: 'Engineering Technology' },
  '1501': { name: 'Architectural Engineering Technology' },
  '1502': { name: 'Civil Engineering Technology' },
  '1503': { name: 'Electrical Engineering Technology' },
  '1504': { name: 'Electromechanical Technology' },
  '1505': { name: 'Environmental Control Technology' },
  '1506': { name: 'Industrial Technology' },
  '1507': { name: 'Quality Control and Safety Technology' },
  '1508': { name: 'Mechanical Engineering Technology' },
  '1509': { name: 'Mining and Petroleum Technology' },
  '1510': { name: 'Construction Engineering Technology' },
  '1511': { name: 'Engineering-Related Technology' },
  '1512': { name: 'Computer Engineering Technology' },
  '1513': { name: 'Drafting and Design Technology' },
  '1514': { name: 'Nuclear Engineering Technology' },
  '1515': { name: 'Engineering-Related Fields' },
  '1517': { name: 'Energy Systems Technology' },
  '1599': { name: 'Other Engineering Technology' },
  '1601': { name: 'Linguistics and Language Studies' },
  '1603': { name: 'East Asian Languages', sentenceName: 'East Asian languages' },
  '1604': { name: 'Slavic and Baltic Languages', sentenceName: 'Slavic and Baltic languages' },
  '1605': { name: 'Germanic Languages', sentenceName: 'Germanic languages' },
  '1609': { name: 'Romance Languages', sentenceName: 'Romance languages' },
  '1611': { name: 'Middle Eastern Languages', sentenceName: 'Middle Eastern languages' },
  '1616': { name: 'American Sign Language', sentenceName: 'American Sign Language' },
  '1699': { name: 'Other Foreign Languages' },
  '1901': { name: 'Family and Consumer Sciences' },
  '1902': { name: 'Family and Consumer Sciences Business' },
  '1904': { name: 'Family and Consumer Economics' },
  '1905': { name: 'Foods and Nutrition' },
  '1906': { name: 'Housing and Human Environments' },
  '1907': { name: 'Human Development and Family Studies' },
  '1909': { name: 'Apparel and Textiles' },
  '1999': { name: 'Other Family and Consumer Sciences' },
  '2200': { name: 'Legal Studies' },
  '2202': { name: 'Advanced Legal Studies' },
  '2203': { name: 'Paralegal Studies' },
  '2299': { name: 'Other Legal Studies' },
  '2301': { name: 'English', sentenceName: 'English' },
  '2313': { name: 'Writing and Rhetoric' },
  '2314': { name: 'Literature' },
  '2399': { name: 'Other English Studies' },
  '2401': { name: 'Liberal Arts and General Studies' },
  '2501': { name: 'Library Science' },
  '2503': { name: 'Library Assisting' },
  '2601': { name: 'Biology' },
  '2602': { name: 'Biochemistry and Molecular Biology' },
  '2603': { name: 'Botany' },
  '2604': { name: 'Cell Biology and Anatomy' },
  '2605': { name: 'Microbiology' },
  '2607': { name: 'Zoology' },
  '2608': { name: 'Genetics' },
  '2609': { name: 'Physiology and Pathology' },
  '2610': { name: 'Pharmacology and Toxicology' },
  '2611': { name: 'Bioinformatics and Computational Biology' },
  '2612': { name: 'Biotechnology' },
  '2613': { name: 'Ecology and Evolution' },
  '2615': { name: 'Neuroscience' },
  '2699': { name: 'Other Biological Sciences' },
  '2701': { name: 'Mathematics' },
  '2703': { name: 'Applied Mathematics' },
  '2705': { name: 'Statistics' },
  '2799': { name: 'Other Mathematics' },
  '2805': { name: 'Military Science' },
  '2902': { name: 'Intelligence and Information Operations' },
  '2904': { name: 'Military Systems Technology' },
  '2999': { name: 'Other Military Technologies' },
  '3000': { name: 'Interdisciplinary Studies' },
  '3001': { name: 'Biological and Physical Sciences' },
  '3005': { name: 'Peace and Conflict Studies' },
  '3006': { name: 'Systems Science' },
  '3008': { name: 'Mathematics and Computer Science' },
  '3010': { name: 'Biopsychology' },
  '3011': { name: 'Gerontology' },
  '3012': { name: 'Historic Preservation' },
  '3015': { name: 'Science, Technology, and Society' },
  '3017': { name: 'Behavioral Sciences' },
  '3018': { name: 'Natural Sciences' },
  '3019': { name: 'Nutrition Science' },
  '3020': { name: 'International Studies' },
  '3022': { name: 'Classical Studies' },
  '3023': { name: 'Multicultural and Diversity Studies' },
  '3025': { name: 'Cognitive Science' },
  '3026': { name: 'Cultural Studies' },
  '3027': { name: 'Human Biology' },
  '3028': { name: 'Dispute Resolution' },
  '3029': { name: 'Maritime Studies' },
  '3030': { name: 'Computational Science' },
  '3031': { name: 'Human-Computer Interaction' },
  '3032': { name: 'Marine Science' },
  '3033': { name: 'Sustainability Studies' },
  '3099': { name: 'Other Interdisciplinary Studies' },
  '3101': { name: 'Parks and Recreation' },
  '3103': { name: 'Recreation Management' },
  '3105': { name: 'Kinesiology and Exercise Science' },
  '3106': { name: 'Outdoor Education' },
  '3199': { name: 'Other Recreation and Kinesiology' },
  '3201': { name: 'Basic Skills and Developmental Education' },
  '3401': { name: 'Health-Related Skills' },
  '3601': { name: 'Leisure and Recreational Activities' },
  '3701': { name: 'Personal Awareness and Self-Improvement' },
  '3801': { name: 'Philosophy' },
  '3802': { name: 'Religious Studies' },
  '3899': { name: 'Other Philosophy and Religion' },
  '3902': { name: 'Bible Studies', sentenceName: 'Bible studies' },
  '3903': { name: 'Missions and Missiology' },
  '3904': { name: 'Religious Education' },
  '3905': { name: 'Religious Music and Worship' },
  '3906': { name: 'Theology and Ministry' },
  '3907': { name: 'Pastoral Counseling and Ministries' },
  '4001': { name: 'Physical Sciences' },
  '4002': { name: 'Astronomy and Astrophysics' },
  '4004': { name: 'Atmospheric Science and Meteorology' },
  '4005': { name: 'Chemistry' },
  '4006': { name: 'Geology and Earth Science' },
  '4008': { name: 'Physics' },
  '4010': { name: 'Materials Science' },
  '4099': { name: 'Other Physical Sciences' },
  '4100': { name: 'General Science Technology' },
  '4101': { name: 'Biology and Biotechnology Technology' },
  '4102': { name: 'Nuclear and Industrial Radiologic Technology' },
  '4103': { name: 'Physical Science Technology' },
  '4199': { name: 'Other Science Technology' },
  '4201': { name: 'Psychology' },
  '4227': { name: 'Experimental Psychology' },
  '4228': { name: 'Clinical and Counseling Psychology' },
  '4299': { name: 'Other Psychology' },
  '4301': { name: 'Criminal Justice' },
  '4302': { name: 'Fire Science' },
  '4303': { name: 'Homeland Security' },
  '4304': { name: 'Security Science and Technology' },
  '4399': { name: 'Other Protective Services' },
  '4400': { name: 'Human Services' },
  '4402': { name: 'Community Organization and Advocacy' },
  '4404': { name: 'Public Administration' },
  '4405': { name: 'Public Policy' },
  '4407': { name: 'Social Work' },
  '4499': { name: 'Other Public and Social Services' },
  '4501': { name: 'Social Sciences' },
  '4502': { name: 'Anthropology' },
  '4503': { name: 'Archaeology' },
  '4504': { name: 'Criminology' },
  '4506': { name: 'Economics' },
  '4507': { name: 'Geography' },
  '4509': { name: 'International Relations' },
  '4510': { name: 'Political Science' },
  '4511': { name: 'Sociology' },
  '4512': { name: 'Urban Studies' },
  '4513': { name: 'Sociology and Anthropology' },
  '4599': { name: 'Other Social Sciences' },
  '4600': { name: 'Construction Trades' },
  '4601': { name: 'Masonry' },
  '4602': { name: 'Carpentry' },
  '4603': { name: 'Electrician Training' },
  '4604': { name: 'Construction Finishing and Inspection' },
  '4605': { name: 'Plumbing' },
  '4699': { name: 'Other Construction Trades' },
  '4701': { name: 'Electronics Repair' },
  '4702': { name: 'HVAC' },
  '4703': { name: 'Heavy Equipment Maintenance' },
  '4704': { name: 'Precision Systems Repair' },
  '4706': { name: 'Vehicle Maintenance and Repair' },
  '4799': { name: 'Other Mechanic and Repair Training' },
  '4805': { name: 'Welding and Machining' },
  '4807': { name: 'Woodworking' },
  '4899': { name: 'Other Precision Production' },
  '4901': { name: 'Aviation' },
  '4902': { name: 'Truck Driving and Equipment Operation' },
  '4903': { name: 'Marine Transportation' },
  '5001': { name: 'Visual and Performing Arts' },
  '5002': { name: 'Crafts and Folk Art' },
  '5003': { name: 'Dance' },
  '5004': { name: 'Design and Applied Arts' },
  '5005': { name: 'Theatre' },
  '5006': { name: 'Film and Photography' },
  '5007': { name: 'Fine and Studio Arts' },
  '5009': { name: 'Music' },
  '5010': { name: 'Arts Management' },
  '5099': { name: 'Other Visual and Performing Arts' },
  '5100': { name: 'Health Sciences' },
  '5102': { name: 'Communication Sciences and Disorders' },
  '5105': { name: 'Advanced Dentistry' },
  '5106': { name: 'Dental Hygiene and Assisting' },
  '5107': { name: 'Health and Medical Administration' },
  '5108': { name: 'Allied Health and Medical Assisting' },
  '5109': { name: 'Diagnostic and Treatment Professions' },
  '5110': { name: 'Medical Laboratory Science' },
  '5111': { name: 'Pre-Health Studies' },
  '5112': { name: 'Medicine' },
  '5115': { name: 'Mental Health and Addiction Services' },
  '5118': { name: 'Ophthalmic and Optometric Services' },
  '5120': { name: 'Pharmacy and Pharmaceutical Sciences' },
  '5122': { name: 'Public Health' },
  '5123': { name: 'Rehabilitation and Therapy' },
  '5126': { name: 'Health Aides and Attendants' },
  '5127': { name: 'Medical Illustration and Informatics' },
  '5131': { name: 'Dietetics' },
  '5132': { name: 'Health Professions Education and Ethics' },
  '5133': { name: 'Alternative Medicine' },
  '5135': { name: 'Massage Therapy' },
  '5136': { name: 'Movement and Mind-Body Therapies' },
  '5138': { name: 'Nursing' },
  '5139': { name: 'Practical Nursing' },
  '5199': { name: 'Other Health Professions' },
  '5201': { name: 'Business' },
  '5202': { name: 'Business Administration' },
  '5203': { name: 'Accounting' },
  '5204': { name: 'Office Administration' },
  '5205': { name: 'Business Communication' },
  '5206': { name: 'Business Economics' },
  '5207': { name: 'Entrepreneurship' },
  '5208': { name: 'Finance' },
  '5209': { name: 'Hospitality Management' },
  '5210': { name: 'Human Resources' },
  '5211': { name: 'International Business' },
  '5212': { name: 'Management Information Systems' },
  '5213': { name: 'Management Science' },
  '5214': { name: 'Marketing' },
  '5215': { name: 'Real Estate' },
  '5217': { name: 'Insurance' },
  '5218': { name: 'Sales and Merchandising' },
  '5219': { name: 'Specialized Sales and Merchandising' },
  '5220': { name: 'Construction Management' },
  '5299': { name: 'Other Business' },
  '5401': { name: 'History' },
}

// Degree abbreviations that are common and correct for every program with this
// CIP code and credential level. Everything else uses the credential name.
export const DEGREE_ABBREVIATIONS: Record<string, Partial<Record<number, string>>> = {
  '5138': { 3: 'BSN', 2: 'ADN' },
}
