/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchoolsSchoolSlugProgramSlugRouteImport } from './routes/schools/$schoolSlug/$programSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsSchoolSlugProgramSlugRoute =
  SchoolsSchoolSlugProgramSlugRouteImport.update({
    id: '/schools/$schoolSlug/$programSlug',
    path: '/schools/$schoolSlug/$programSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/schools/$schoolSlug/$programSlug': typeof SchoolsSchoolSlugProgramSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/schools/$schoolSlug/$programSlug': typeof SchoolsSchoolSlugProgramSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/schools/$schoolSlug/$programSlug': typeof SchoolsSchoolSlugProgramSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/schools/$schoolSlug/$programSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/schools/$schoolSlug/$programSlug'
  id: '__root__' | '/' | '/schools/$schoolSlug/$programSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SchoolsSchoolSlugProgramSlugRoute: typeof SchoolsSchoolSlugProgramSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools/$schoolSlug/$programSlug': {
      id: '/schools/$schoolSlug/$programSlug'
      path: '/schools/$schoolSlug/$programSlug'
      fullPath: '/schools/$schoolSlug/$programSlug'
      preLoaderRoute: typeof SchoolsSchoolSlugProgramSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SchoolsSchoolSlugProgramSlugRoute: SchoolsSchoolSlugProgramSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
